version: '3.8'

networks:
  odoo: {}
  proxy:
    external: true

volumes:
  odoo-data: {}
  odoo-db: {}

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
    volumes:
      - odoo-db:/var/lib/postgresql/data
    networks:
      - odoo

  app:
    image: odoo:16
    links:
      - db:db
    depends_on:
      - db
    networks:
      - odoo
      - proxy
    volumes:
      - odoo-data:/var/lib/odoo
    labels:
      caddy: $ODOO_HOST
      caddy.reverse_proxy: "{{ upstreams 8069 }}"
