version: '3.8'

networks:
  odoo: {}
  proxy:
    external: true

volumes:
  data:
  pgdata:

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - odoo

  app:
    image: odoo:16
    command: -i base
    environment:
      - HOST=db
      - USER=$DB_USER
      - PASSWORD=$DB_PASSWORD
    depends_on:
      - db
    networks:
      - odoo
      - proxy
    volumes:
      - data:/var/lib/odoo
    labels:
      caddy: $ODOO_HOST
      caddy.reverse_proxy: "{{ upstreams 8069 }}"
