version: '3.8'

networks:
  proxy:
    external: true

volumes: 
  youtrack: {}

services:
  app: 
    image: jetbrains/youtrack:${APP_VERSION}
    volumes: 
      - youtrack:/opt/youtrack
    networks:
      - proxy
    labels:
      caddy: $APP_FQDN
      caddy.reverse_proxy: "{{ upstreams 8080 }}"