version: '3.8'

networks:
  proxy:
    external: true

volumes: 
  youtrack: {}

services:
  app: 
    image: jetbrains/youtrack:${APP_VERSION}
    volume: 
      - youtrack/conf:/opt/youtrack/conf
      - youtrack/data:/opt/youtrack/data
      - youtrack/logs:/opt/youtrack/logs
      - youtrack/backup:/opt/youtrack/backup
    networks:
      - proxy
    labels:
      caddy: $APP_FQDN
      caddy.reverse_proxy: "{{ upstreams 8080 }}"