version: '3.8'

networks:
  graylog: {}
  
volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASE_DIR}/mongo
  index_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASE_DIR}/elasticsearch      
  graylog_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BASE_DIR}/data

services:
  mongo:
    image: mongo:5.0.13
    volumes:
      - mongo_data:/data/db
    networks:
      - graylog

  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1g"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - cluster.name=graylog-cluster
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - index_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1.5g
    networks:
      - graylog  

  graylog:
    image: graylog/graylog:5.1
    environment:
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_EXTERNAL_URI: ${GRAYLOG_HTTP_EXTERNAL_URI}
      GRAYLOG_ELASTICSEARCH_HOSTS:  'http://elasticsearch:9200'
      GRAYLOG_MONGODB_URI: 'mongodb://mongo:27017/graylog'
    entrypoint: /usr/bin/tini -- wait-for-it -t 30 elasticsearch:9200 -- /docker-entrypoint.sh
    volumes:
      - graylog_data:/usr/share/graylog/data
    networks:
      - graylog
    deploy:
      resources:
        limits:
          memory: 3G
    depends_on:
      - elasticsearch
      - mongo
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # Syslog TCP
      - 514:514
